// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpA43zMmddeW21hxI7HXlfggeSyHsZBA8',
    appId: '1:282030367496:web:3fbacf9de28ab0f44082bd',
    messagingSenderId: '282030367496',
    projectId: 'restaurant-a321f',
    authDomain: 'restaurant-a321f.firebaseapp.com',
    storageBucket: 'restaurant-a321f.firebasestorage.app',
    measurementId: 'G-81M3NLV0WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_SEHQkN4-_LPpnJyh3QbrAhlvmxMJwHk',
    appId: '1:282030367496:android:5ad4be150813dfec4082bd',
    messagingSenderId: '282030367496',
    projectId: 'restaurant-a321f',
    storageBucket: 'restaurant-a321f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW-1miQUjFvdLrT2FCNWqD7M1C7mBcLvs',
    appId: '1:282030367496:ios:bec14a96b5ba0ba04082bd',
    messagingSenderId: '282030367496',
    projectId: 'restaurant-a321f',
    storageBucket: 'restaurant-a321f.firebasestorage.app',
    iosBundleId: 'com.example.flutterRestaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW-1miQUjFvdLrT2FCNWqD7M1C7mBcLvs',
    appId: '1:282030367496:ios:bec14a96b5ba0ba04082bd',
    messagingSenderId: '282030367496',
    projectId: 'restaurant-a321f',
    storageBucket: 'restaurant-a321f.firebasestorage.app',
    iosBundleId: 'com.example.flutterRestaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpA43zMmddeW21hxI7HXlfggeSyHsZBA8',
    appId: '1:282030367496:web:5859ad33927119804082bd',
    messagingSenderId: '282030367496',
    projectId: 'restaurant-a321f',
    authDomain: 'restaurant-a321f.firebaseapp.com',
    storageBucket: 'restaurant-a321f.firebasestorage.app',
    measurementId: 'G-LWF2XRTBQ5',
  );
}
