// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_dH3Gf_FAv84qWMrp1NLb71T1KdZ5cLk',
    appId: '1:976694098957:web:06f1bee6b4708dc29d2944',
    messagingSenderId: '976694098957',
    projectId: 'restaurant-7d5e1',
    authDomain: 'restaurant-7d5e1.firebaseapp.com',
    storageBucket: 'restaurant-7d5e1.firebasestorage.app',
    measurementId: 'G-FW1DKHJDG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-5AixR5zcz7dWVI9hYp6rHQr7wMz82sk',
    appId: '1:976694098957:android:05d34e4b2cb4a1459d2944',
    messagingSenderId: '976694098957',
    projectId: 'restaurant-7d5e1',
    storageBucket: 'restaurant-7d5e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdSCd8muOHc7Zz_2ijrWF0r0T_TPtPAZU',
    appId: '1:976694098957:ios:deb080d57e7f2dea9d2944',
    messagingSenderId: '976694098957',
    projectId: 'restaurant-7d5e1',
    storageBucket: 'restaurant-7d5e1.firebasestorage.app',
    iosBundleId: 'com.example.flutterRestaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdSCd8muOHc7Zz_2ijrWF0r0T_TPtPAZU',
    appId: '1:976694098957:ios:deb080d57e7f2dea9d2944',
    messagingSenderId: '976694098957',
    projectId: 'restaurant-7d5e1',
    storageBucket: 'restaurant-7d5e1.firebasestorage.app',
    iosBundleId: 'com.example.flutterRestaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_dH3Gf_FAv84qWMrp1NLb71T1KdZ5cLk',
    appId: '1:976694098957:web:8459d8792cdeca759d2944',
    messagingSenderId: '976694098957',
    projectId: 'restaurant-7d5e1',
    authDomain: 'restaurant-7d5e1.firebaseapp.com',
    storageBucket: 'restaurant-7d5e1.firebasestorage.app',
    measurementId: 'G-J7NM793SRY',
  );

}